controller_frequency: 20.0

planner_frequency: 0.0
planner_patience: 5.0
oscillation_timeout: 0.0

base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

recovery_behaviors: []

